version: "3.9"

services:
  database:
    build: ./database
    container_name: my-postgres
    restart: always
    env_file:
      - .env
    networks:
      - back-db
    volumes:
      - db-data:/var/lib/postgresql/data

  backend:
    build: ./backend
    container_name: backend
    restart: always
    depends_on:
      - database
    env_file:
      - .env
    networks:
      - back-db
      - front-back

  httpd:
    build: ./httpd
    container_name: httpd
    restart: always
    depends_on:
      - backend
    ports:
      - "80:80"
    networks:
      - front-back

  adminer:
    image: adminer
    container_name: adminer
    restart: always
    ports:
      - "8090:8080"
    networks:
      - back-db

# --- Réseaux ---
networks:
  front-back:
  back-db:

# --- Volume pour la base ---
volumes:
  db-data:
